In [1]:
###pip install pyDecision

import numpy as np
# Import AHP
from pyDecision.algorithm import ahp_method


In [4]:
# Parameters
weight_derivation = 'geometric' # 'mean'; 'geometric' or 'max_eigen'

# Dataset
dataset = np.array([
  #g1     g2     g3
  [1    ,   3  ,   5],   #g1
  [1/3  ,   1  ,   1],   #g2
  [1/5  ,   1  ,   1],   #g3
])

# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

# Weigths
for i in range(0, weights.shape[0]):
  print('w(g'+str(i+1)+'): ', round(weights[i], 4))
  
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
  print('The solution is consistent')


w(g1):  0.6586
w(g2):  0.1852
w(g3):  0.1562
RC: 0.0251
The solution is consistent


In [5]:
#kostas fix this

In [6]:
# Parameters
weight_derivation = 'geometric' # 'mean'; 'geometric' or 'max_eigen'

# Dataset
dataset = np.array([
  #g1     g2     g3
  [1    ,   3  ,   5],   #g1
  [1/3  ,   1  ,   1],   #g2
  [1/5  ,   1  ,   1],   #g3
])

# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

# Weigths
for i in range(0, weights.shape[0]):
  print('w(g'+str(i+1)+'): ', round(weights[i], 4))
  
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
  print('The solution is consistent')


w(g1):  0.6586
w(g2):  0.1852
w(g3):  0.1562
RC: 0.0251
The solution is consistent


In [7]:
#now move on to calculate priority scores, Dec 2025, Kostas

In [8]:
data_alternatives_by_pillars_3x3 = np.loadtxt("input_data_for_ahp_4_1_aluminium.txt")
print(data_alternatives_by_pillars_3x3)

[[  0.   0. 100.]
 [100. 100.   0.]
 [ 65.  50.  48.]]


In [9]:
print(weights)

[0.65864419 0.18517401 0.15618181]


In [10]:
priority_scores = data_alternatives_by_pillars_3x3 @ np.transpose(weights)
print(priority_scores)

[15.61818064 84.38181936 59.56729918]


In [11]:
result = np.zeros((3,2))
result[:,0]=[1,2,3]
result[:,1]=priority_scores
print(result)

[[ 1.         15.61818064]
 [ 2.         84.38181936]
 [ 3.         59.56729918]]


In [10]:
for j in range(3):
    print("priority score... alternative...",j+1,"...is...:",round(priority_scores[j],3))

priority score... alternative... 1 ...is...: 15.618
priority score... alternative... 2 ...is...: 84.382
priority score... alternative... 3 ...is...: 59.567
