In [1]:
###pip install pyDecision

import numpy as np
# Import AHP
from pyDecision.algorithm import ahp_method


In [3]:
# Parameters
weight_derivation = 'geometric' # 'mean'; 'geometric' or 'max_eigen'

# Dataset
dataset = np.array([
  #g1     g2     g3
  [1    ,   3  ,   1/4],   #g1
  [1/3  ,   1  ,   1/6],   #g2
  [4    ,   6  ,   1],     #g3
])

# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

# Weigths
for i in range(0, weights.shape[0]):
  print('w(g'+str(i+1)+'): ', round(weights[i], 4))
  
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
  print('The solution is consistent')


w(g1):  0.2176
w(g2):  0.0914
w(g3):  0.691
RC: 0.0462
The solution is consistent


In [3]:
#kostas fix this

In [4]:
# Parameters
weight_derivation = 'geometric' # 'mean'; 'geometric' or 'max_eigen'

# Dataset
dataset = np.array([
  #g1     g2     g3
  [1    ,   3  ,   1/4],   #g1
  [1/3  ,   1  ,   1/6],   #g2
  [4    ,   6  ,   1],     #g3
])

# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

# Weigths
for i in range(0, weights.shape[0]):
  print('w(g'+str(i+1)+'): ', round(weights[i], 4))
  
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
  print('The solution is consistent')


w(g1):  0.2176
w(g2):  0.0914
w(g3):  0.691
RC: 0.0462
The solution is consistent


In [6]:
#now move on to calculate priority scores, Dec 2025, Kostas

In [7]:
data_alternatives_by_pillars_3x3 = np.loadtxt("input_data_for_ahp_4_1_plastics.txt")
print(data_alternatives_by_pillars_3x3)

[[ 70.  11.  90.]
 [ 70.  38. 100.]
 [ 70.  11.  66.]
 [ 70.  38.  77.]
 [100.   6.  23.]
 [100.  35.  36.]
 [100.   6.   0.]
 [100.  35.  13.]
 [  0.   0.   0.]
 [ 70.  93.  90.]
 [ 70.  93. 100.]
 [ 70.  93.  66.]
 [ 70.  93.  77.]
 [100. 100.  23.]
 [100. 100.  36.]
 [100. 100.   0.]
 [100. 100.  13.]
 [  0.  93.   0.]]


In [9]:
print(weights)

[0.21763848 0.09140243 0.69095909]


In [10]:
priority_scores = data_alternatives_by_pillars_3x3 @ np.transpose(weights)
print(priority_scores)

[78.42643832 87.80389491 61.84342012 71.9118358  38.2043213  49.83746003
 22.3122622  33.94540093  0.         85.92143778 92.83102869 69.33841958
 76.93896959 46.79614995 55.77861814 30.90409084 39.88655903  8.50042621]


In [11]:
result = np.zeros((18,2))
result[:,0]=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
result[:,1]=priority_scores
print(result)

[[ 1.         78.42643832]
 [ 2.         87.80389491]
 [ 3.         61.84342012]
 [ 4.         71.9118358 ]
 [ 5.         38.2043213 ]
 [ 6.         49.83746003]
 [ 7.         22.3122622 ]
 [ 8.         33.94540093]
 [ 9.          0.        ]
 [10.         85.92143778]
 [11.         92.83102869]
 [12.         69.33841958]
 [13.         76.93896959]
 [14.         46.79614995]
 [15.         55.77861814]
 [16.         30.90409084]
 [17.         39.88655903]
 [18.          8.50042621]]


In [12]:
for j in range(18):
    print("priority score... alternative...",j+1,"...is...:",round(priority_scores[j],3))

priority score... alternative... 1 ...is...: 78.426
priority score... alternative... 2 ...is...: 87.804
priority score... alternative... 3 ...is...: 61.843
priority score... alternative... 4 ...is...: 71.912
priority score... alternative... 5 ...is...: 38.204
priority score... alternative... 6 ...is...: 49.837
priority score... alternative... 7 ...is...: 22.312
priority score... alternative... 8 ...is...: 33.945
priority score... alternative... 9 ...is...: 0.0
priority score... alternative... 10 ...is...: 85.921
priority score... alternative... 11 ...is...: 92.831
priority score... alternative... 12 ...is...: 69.338
priority score... alternative... 13 ...is...: 76.939
priority score... alternative... 14 ...is...: 46.796
priority score... alternative... 15 ...is...: 55.779
priority score... alternative... 16 ...is...: 30.904
priority score... alternative... 17 ...is...: 39.887
priority score... alternative... 18 ...is...: 8.5
